### ISSUE TITLE
Any way to determine if a service is already running?

### ISSUE THREAD

**Issue by killroyboy** [coreybutler/node-mac#22]
I would like to be able to detect if the service is already running.

**Comment by coreybutler** [comment]
Closing due to age.

If you landed here from a search engine, the way to determine if the service is running is to run a `ps -ef | grep process_name`. To determine if the service is installed, look for the existence of the plist file in the `/Library/LaunchAgents` or `/Library/LaunchDaemons` directory.

This library primarily focuses on installing/uninstalling. It really requires another tool/process to determine if a process is running (since this code only executes when the process is actually running).
