### ISSUE TITLE
support running a binary, vs a pure node script

### ISSUE THREAD

**Issue by cdaringe** [coreybutler/node-mac#24]
# problem

- i have needs to run _other_ types of scripts and bins that aren't node scripts

# discussion

- `fork` => `spawn` should do the trick

**Comment by coreybutler** [comment]
Closing (mostly) due to age (apologies).

The whole point of this project is to be a wrapper around node scripts. To run other scripts as daemons, I recommend generating the appropriate plist files using the [plist](https://www.npmjs.com/package/plist) to produce the assets required.

The fork is done specifically to prevent detaching the process from the wrapper.
